### ISSUE TITLE
Support querying multiple repositories?

### ISSUE THREAD

**Issue by KyleAMathews** [mosch/gatsby-source-github#1]
This would be a handy feature.

Perhaps the node types could then include the repository name in them e.g. allGithubGatsbyFile or alternatively you could just filter by the repository name when writing queries.

**Comment by mosch** [comment]
Hey @KyleAMathews,
thanks for bringing this up - I was thinking about the same. But actually I just include the plugin multiple times with different configurations. Kind of the same like I would do with the gatsby-source-filesystem. 

You you think there would be benefits by making one configuration containing multiple repositories?

**Comment by KyleAMathews** [comment]
>actually I just include the plugin multiple times with different configurations

That actually sounds pretty reasonable!
